[project]
name = "compass-synoptic-sims"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "bottleneck>=1.4.2",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "scipy>=1.15.2",
    "xarray>=2025.3.1",
]
